### ISSUE TITLE
PureScript 0.12 Support?

### ISSUE THREAD

**Issue by RAbraham** [lpil/purescript-aws-lambda-express#2]
Hi,
Thanks a lot for making this library. I'm getting errors trying to build this with PureScript 0.12.0. What I did was
```bash
mkdir myproject and cd myproject
pulp init
pulp build // This worked
bower install --save purescript-aws-lambda-express purescript-express //There were some library version conflicts here
npm install --save aws-serverless-express express

```
And then I tried
```bash
pulp build
```

and I got a lot of 
```
Module Data.SomeType has been defined multiple times
```

I'm using VS Code and I don't know if that's conflicting with `pulp` and creating multiple modules?
Let me know what I'm doing wrong. Thanks!

**Comment by lpil** [comment]
Good shout. I've not written any Purescript since 0.12 came out, so perhaps there's a more up-to-date person than me who would like to have a go?

**Comment by RAbraham** [comment]
Hi @lpil , I have submitted a PR for 0.12 update.  Please let me know if you would like more changes.
